name: CI/CD for Dockerized Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Build The Docker Image
        id: build
        run: |
          docker build . --file DockerFile --tag workflow-test:latest
          echo "image-tag=latest" >> $GITHUB_ENV

  build-and-test:
    needs: dockerbuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List Docker Images
        run: docker images

      - name: Run Docker Container and Tests
        run: |
          docker run --rm workflow-test:latest pytest

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest }}
